# Generated by Django 3.2.8 on 2021-10-14 18:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('display_name', models.CharField(max_length=20)),
                ('phone_number', models.CharField(max_length=20)),
                ('bio', models.CharField(max_length=500)),
                ('suspended', models.BooleanField()),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('text_content', models.CharField(blank=True, max_length=200)),
                ('img_content', models.ImageField(blank=True, upload_to='')),
                ('hashtags', models.CharField(blank=True, max_length=200)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='post_user', to='sanctuary.player')),
            ],
        ),
        migrations.CreateModel(
            name='Reply',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reply_created', models.DateTimeField(auto_now_add=True)),
                ('text_content', models.CharField(blank=True, max_length=200)),
                ('img_content', models.ImageField(blank=True, upload_to='')),
                ('post_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='post', to='sanctuary.post')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reply_user', to='sanctuary.player')),
            ],
        ),
        migrations.CreateModel(
            name='GameData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('save_file', models.JSONField()),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='gamedata', to='sanctuary.player')),
            ],
        ),
    ]
