# Generated by Django 3.2.8 on 2021-10-14 21:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('sanctuary', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='player',
            name='display_name',
        ),
        migrations.RemoveField(
            model_name='player',
            name='phone_number',
        ),
        migrations.AlterField(
            model_name='post',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='post_user', to=settings.AUTH_USER_MODEL),
        ),
    ]
