# Generated by Django 3.2.8 on 2021-10-12 16:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sanctuary', '0002_alter_post_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='player',
            name='userId',
        ),
        migrations.RemoveField(
            model_name='post',
            name='post_id',
        ),
    ]
